// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1611417410);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1611417530);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1611417170);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1611417290);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1611417650);
user_pref("browser.cache.disk.amount_written", 1022);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.search.region", "KG");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.lastModified", "Fri, 22 Jan 2021 23:33:01 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.cache.lastUpdate", 1611417411);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20200629235513");
user_pref("extensions.lastAppVersion", "68.10.0");
user_pref("extensions.lastPlatformVersion", "68.10.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"wetransfer@extensions.thunderbird.net\":\"9f349d3c-c310-4c25-855d-1b8ac52f8490\",\"default-theme@mozilla.org\":\"b70f6239-6217-42d3-8b5b-586dee51333f\",\"yandex@search.mozilla.org\":\"56c65370-ca8d-4e34-8732-a1266615d111\",\"google@search.mozilla.org\":\"a6ed8e1e-3a79-476a-8823-858dc02720df\",\"ddg@search.mozilla.org\":\"f4d9a06d-4230-4dc6-ac27-ff164e5c873a\",\"ozonru@search.mozilla.org\":\"dec3da39-f210-4b21-92d0-aa7f2bf99d9c\",\"priceru@search.mozilla.org\":\"d4d2906d-30dd-416e-8b33-ae7efbdc47bc\",\"wikipedia@search.mozilla.org\":\"7f8de3ef-9cfc-4896-bc10-ff5f4fa71cc1\",\"mailru@search.mozilla.org\":\"8fd443c3-f1ac-4d26-8342-2b4ea0d4d98d\"}");
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.append_preconfig_smtpservers.version", 2);
user_pref("mail.default_charsets.migrated", 1);
user_pref("mail.folder.views.version", 1);
user_pref("mail.openMessageBehavior.version", 1);
user_pref("mail.spam.version", 1);
user_pref("mail.ui-rdf.version", 17);
user_pref("mailnews.database.global.datastore.id", "e8be771e-7cf2-478f-aebd-ce4b6c68ed9");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "68.10.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Важное");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Рабочее");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Личное");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "К исполнению");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Отложено");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("security.sandbox.plugin.tempDirSuffix", "67c6934c-4884-4c54-984e-bd7905bc8f40");
user_pref("services.blocklist.pinning.checked", 1611417339);
user_pref("services.settings.clock_skew_seconds", -49);
user_pref("services.settings.last_etag", "\"1611410259245\"");
user_pref("services.settings.last_update_seconds", 1611417339);
user_pref("services.settings.main.hijack-blocklists.last_check", 1611417339);
user_pref("services.settings.main.language-dictionaries.last_check", 1611417339);
user_pref("services.settings.main.sites-classification.last_check", 1611417339);
user_pref("services.settings.security.onecrl.checked", 1611417339);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.telemetry.cachedClientID", "ae351ae6-7d1f-4949-bf0f-a3bcfc03dd8e");
user_pref("toolkit.telemetry.prompted", 2);
