# gamemoded
# Autogenerated from man page /usr/share/man/man8/gamemoded.8.gz
complete -c gamemoded -s r -l request --description 'Toggle gamemode for process.  When no PID given, requests gamemode and pauses.'
complete -c gamemoded -s s -l status --description 'Query the status of gamemode for process When no PID given, queries the statu…'
complete -c gamemoded -s d -l daemonize --description 'Run the daemon as a separate process (daemonize it).'
complete -c gamemoded -s l -l log-to-syslog --description 'Log to syslog.'
complete -c gamemoded -s h -l help --description 'Print help text.'
complete -c gamemoded -s t -l test --description 'Run diagnostic tests on the current installation.'
complete -c gamemoded -s v -l version --description 'Print the version.'

