# idle
# Autogenerated from man page /usr/share/man/man1/idle.1.gz
complete -c idle -s h --description 'PD Print this help message and exit.'
complete -c idle -s n --description 'PD Run IDLE without a subprocess (see Help/IDLE Help for details).'
complete -c idle -s e --description 'PD Open an edit window.'
complete -c idle -s i --description 'PD Open a shell window.'
complete -c idle -s c --description 'PD Run the command in a shell, or.'
complete -c idle -s r --description 'PD Run script from file. PP.'
complete -c idle -s d --description 'PD Enable the debugger.'
complete -c idle -s s --description 'PD Run $IDLESTARTUP or $PYTHONSTARTUP before anything else.'
complete -c idle -s t --description '.'

