# idle-python3
# Autogenerated from man page /usr/share/man/man1/idle-python3.8.1.gz
complete -c idle-python3 -s h --description 'PD Print this help message and exit.'
complete -c idle-python3 -s n --description 'PD Run IDLE without a subprocess (see Help/IDLE Help for details).'
complete -c idle-python3 -s e --description 'PD Open an edit window.'
complete -c idle-python3 -s i --description 'PD Open a shell window.'
complete -c idle-python3 -s c --description 'PD Run the command in a shell, or.'
complete -c idle-python3 -s r --description 'PD Run script from file. PP.'
complete -c idle-python3 -s d --description 'PD Enable the debugger.'
complete -c idle-python3 -s s --description 'PD Run $IDLESTARTUP or $PYTHONSTARTUP before anything else.'
complete -c idle-python3 -s t --description '.'

