# software-properties-gtk
# Autogenerated from man page /usr/share/man/man1/software-properties-gtk.1.gz
complete -c software-properties-gtk -l debug --description 'Print some debug information to the command line.'
complete -c software-properties-gtk -l massive-debug --description 'Print a lot of debug information to the command line.'
complete -c software-properties-gtk -l no-update --description 'No update on repository change (useful if called from an external program).'
complete -c software-properties-gtk -l enable-component --description 'Enable the specified component of the distro\'s repositories [component_arg].'
complete -c software-properties-gtk -l open-tab --description 'Open specific tab number on startup.'
complete -c software-properties-gtk -l enable-ppa --description 'Enable PPA with the given name [ppa_arg] . SS Generic options:.'
complete -c software-properties-gtk -l help --description 'Show help about options.'

