# update-manager
# Autogenerated from man page /usr/share/man/man8/update-manager.8.gz
complete -c update-manager -s h -l help --description 'Show a similar help message.'
complete -c update-manager -s V -l version --description 'Show version.'
complete -c update-manager -l data-dir --description 'Directory that contains the data files.'
complete -c update-manager -s c -l check-dist-upgrades --description 'Check if a new distribution release is available.'
complete -c update-manager -s d -l devel-release --description 'If using the latest supported release, upgrade to the development release.'
complete -c update-manager -s p -l proposed --description 'Upgrade using the latest proposed version of the release upgrader.'
complete -c update-manager -l no-focus-on-map --description 'Do not focus on map when starting.'

