// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.normandy.startupRolloutPrefs.browser.toolbars.bookmarks.2h2020", true);
user_pref("app.normandy.startupRolloutPrefs.network.preload", true);
user_pref("app.normandy.user_id", "711d8d4e-fedf-47d1-8bb1-50bd5df3c726");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1611526218);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1611526206);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1611526191);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1611526338);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1611526248);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.viewableInternally.typeWasRegistered.svg", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.xml", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1611526187);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 104);
user_pref("browser.newtabpage.activity-stream.impressionId", "{9722bac7-b38f-486e-b4ee-093b11bda156}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1611526239719");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1611528013719");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1611526202346");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1611547802346");
user_pref("browser.search.region", "KG");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1611526189");
user_pref("browser.slowStartup.averageTime", 1658);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20210105180113");
user_pref("browser.startup.homepage_override.mstone", "84.0.2");
user_pref("browser.startup.lastColdStartupCheck", 1611526189);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1611526198768");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "84.0.2");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("dom.push.userAgentID", "e4619dcab3d240709940bc8b7a4709e8");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "84.0.2");
user_pref("extensions.lastPlatformVersion", "84.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_picture_in_picture_overrides", true);
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"27a74d9b-6412-494c-aeec-4933f58ccfc4\",\"formautofill@mozilla.org\":\"aa0e53b5-bac2-4f7c-aff9-87ef1e13996c\",\"screenshots@mozilla.org\":\"12f8133c-052e-43e6-abc0-1135956b322d\",\"webcompat-reporter@mozilla.org\":\"b8e7536d-46b0-4fd2-ace9-32d7b23836f0\",\"webcompat@mozilla.org\":\"62ef6769-32b8-45fe-8528-1da159ff3d74\",\"default-theme@mozilla.org\":\"d2339f01-2e89-42da-8ffb-7fd2ecfc9d9b\",\"google@search.mozilla.org\":\"de232b5f-8aa1-468f-95cd-1358ccabc5a0\",\"wikipedia@search.mozilla.org\":\"6aa686bd-ff35-4bca-bc85-40e2215e812c\",\"yandex@search.mozilla.org\":\"ffe9b427-1c76-4330-8616-749a36909f13\",\"ddg@search.mozilla.org\":\"931a5106-b098-47e8-84d0-3c5719d99209\",\"priceru@search.mozilla.org\":\"38576d03-9f55-4d75-9df0-f267bfa59150\",\"mailru@search.mozilla.org\":\"aee773ed-780b-491f-9525-e6bcd6810ef5\",\"ozonru@search.mozilla.org\":\"a9cb5693-339b-44e4-ab4c-cd1d9e240525\"}");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "2fbb2dd3-6c89-443e-a78c-693b01b0b25a");
user_pref("security.sandbox.plugin.tempDirSuffix", "c55c93a0-bd56-4293-9864-d91d69c9baeb");
user_pref("toolkit.startup.last_success", 1611526186);
user_pref("toolkit.telemetry.cachedClientID", "03826c4f-6ea5-4eb0-a86e-6558288b2b86");
user_pref("toolkit.telemetry.previousBuildID", "20210105180113");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
